language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  - BYTIC_VERSION=1.0.*
  - BYTIC_VERSION=0.9.*

before_script:
  - composer require "bytic/controllers:${BYTIC_VERSION}" --no-update
  - composer require "bytic/cookie:${BYTIC_VERSION}" --no-update
  - composer require "bytic/helpers:${BYTIC_VERSION}" --no-update
  - composer require "bytic/orm:${BYTIC_VERSION}" --no-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover coverage.xml